
#'
#' `rgraphsampler` is a simple R interface for calling `graph_sampler`'s C code (v3.1) from R
#' and manipulating the results, designed primarily for non-Linux users.
#'
#' The objective of `rgraphsampler` is two-fold:
#'
#'   1. To make available to R users a convenient tool for performing inference in `graph_sampler`
#'   2. To make working with outputs of `graph_sampler` analyses easier.
#'
#'
#' @section Basic use case:
#'
#' `graph_sampler` scripts are ran with `rgs()`; `rgs(file_in, file_out)` is equivalent
#' to `graph_sampler <file_in> <file_out>`
#' See `?rgs` for examples and `vignette("rgraphsampler")` for a short demonstration.
#'
#'
#' @section Differences between R and C versions:
#'
#' R version is fully featured in that it directly uses unmodified `graph_sampler` code within
#' the package. However, GSL versions of functions are disabled to decrease dependencies for non-Linux users.
#' Therefore the results obtained through R version should be equivalent to running non-GSL version
#' of `graph_sampler`.
#'
#' @section Known bugs, state of the project:
#'
#' Due to nature of `bison` parsing engine (the tool for reading in input scripts), when errors
#' occur (e.g. due to malformed input script) in the parser, it is recommended to unload the
#' dynamic library before working with any other scripts. This helps R delete some static variables
#' generated by the parser, which otherwise may not reset on errors. To unload the namespace use
#' `unloadNamespace("rgraphsampler")`
#'
#' All of the code included here has been tested with the scripts from `graph_sampler`'s (C version)
#' testing suite. That means this package produces outputs identical to GSL version of `graph_sampler`
#' that we've tested. However, there is no automated testing of R code and caution is advised.
#'
#' @keywords internal
"_PACKAGE"
