#' rgs: R graph_sampler interface
#'
#' Run [`graph_sampler`](http://www.nongnu.org/graphsampler/) software from inside R.
#' @param file_in file name for a valid `graph_sampler` input script (see syntax
#'                [here](http://www.nongnu.org/graphsampler/graph_sampler.html#Input-file-syntax);
#'                comprehensive list of examples is also attached -- see Details)
#' @param file_out file name (prefix) for output files generated by `graph_sampler`
#' @param return_result logical; if TRUE, call to `get_gs_result()` is made at the end of the function
#' @param node_names passed to `get_gs_result()` if `return_result = TRUE`
#' @return If `return_result = FALSE`, nothing is returned; standard graph_sampler output is printed
#'         in the terminal and output files generated as requested, under `file_out` file name.
#'         If `return_result = TRUE`, output is an `rgs` object of `get_gs_result()`.
#' @details This simple function allows running C software graph_sampler
#'          inside R. All of the graph_sampler configuration is achieved
#'          by using a config script (`file_in`), which is identical to
#'          [the input for C version](http://www.nongnu.org/graphsampler/graph_sampler.html#Running-Graph_005fSampler).
#'          30 examples of scripts are attached within this package.
#'          They can be accessed by `system.file()`, like in the example below.
#'          For the full list use `list.files(system.file(package="rgraphsampler", "test_scripts"))`.
#' @examples
#' script_file <- system.file(package="rgraphsampler",
#'                            "test_scripts", "script_test_1.txt")
#' # to review built-in examples try
#' # file.show(script_file)
#'
#' # Will generate graph_sampler output files in the current working directory
#' rgs(file_in = script_file,
#'     file_out = "gs_output")
#'
#' @author Witold Wiecek
#' @useDynLib rgraphsampler
#' @export

rgs <- function(file_in = "script.txt",
                file_out = "output",
                return_result = TRUE,
                node_names = NULL){
  # library.dynam("rgraphsampler", "rgraphsampler", .libPaths())
  if(!file.exists(file_in))
    stop("No input file.")
  foo <- .C("gsmain",
            file_in,
            file_out)
  if(return_result)
    get_gs_result(file_out, node_names)
}
